name: CI/CD Pipeline for Strapi

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Build Strapi application
        run: npm run 
      - name: for pretty
        run: yarn run

      - name: Test Strapi application
        run: npm test 
      - name: Package application
        run: |
          mkdir -p dist
          # Example: Create a tar file
          zip -r dist/app.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-package
          path: dist/app.zip 
